module Guesser

    def guess
        p @code #this is generated by random code of 4 digits
        function_end = false
        guessed_code = []
        p "enter ur code"
        until function_end
            loop do 
                p "Please enter your code of 4-digits"
                current_code = gets.chomp.to_s.split("")

                if current_code.length == 4
                guessed_code = current_code 
                puts "Hello"
                giveHint(guessed_code)
                break
                end
                
            end
            
            if guessed_code.eql?(@code) 
                p "Well done #{@name} you did a good job!"
                function_end = true
            end 
        end
        
    end

    def giveHint(code)
        
    end
end
